config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'welcome#index'

  namespace :admin do
    resources :clients
  end

  namespace :culture do
    resources :books
  end

  namespace :contacts do
    resources :people
  end

end

app/models/client.rb
# == Schema Information
#
# Table name: clients
#
#  id          :uuid             not null, primary key
#  short_name  :string(25)       not null
#  full_name   :string
#  users_count :integer          default(0), not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Client < ActiveRecord::Base
  has_paper_trail

  has_many :users

  validates :short_name, :full_name, presence: true
end

app/controllers/admin/clients_controller.rb
module Admin
  class ClientsController < AdminController

    def index
      @clients = Client.order(:short_name)
    end
  end
end

app/views/admin/clients/index.html.slim
h1 Client Listing

hr

.col-lg-12
  table.table.table-striped.table-hover
    thead
      tr
        th ID
        th Short Name
        th Full Name
        th # of Users
        th
    tbody
      - @clients.each do |client|
        tr
          td= client.id
          td= client.short_name
          td= client.full_name
          td= client.users_count
          td
            = link_to "Manage", edit_admin_client_path(client)
            | &nbsp;|&nbsp;
            = link_to "Delete", admin_client_path(client), method: :delete, data: { confirm: "Are you sure?"}