config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'welcome#index'

  namespace :admin do
    resources :clients
  end

  namespace :culture do
    resources :books
  end

  namespace :contacts do
    resources :people
  end

end

app/models/contacts.rb
module Contacts
  def self.table_name_prefix
    'contacts_'
  end
end

app/models/contacts/person.rb
# == Schema Information
#
# Table name: contacts_people
#
#  id         :uuid             not null, primary key
#  user_id    :uuid             not null
#  first_name :string
#  last_name  :string
#  email      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_contacts_people_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_10f8f76eb2  (user_id => users.id)
#

class Contacts::Person < ActiveRecord::Base
  has_paper_trail meta: { user_id: :user_id }
  belongs_to :user

  validates :user_id, presence: true

  validate :has_significant_attribute

  def has_significant_attribute
    if first_name.blank? && last_name.blank? && email.blank?
      errors[:base] << "Contact must have a first name, last name OR email"
    end
  end
end

app/controllers/contacts/people_controller.rb
module Contacts
  class PeopleController < AuthenticatedController
    responders :flash, :collection

    before_action :set_person, only: [:show, :edit, :update, :destroy]

    def index
      @people = current_user.contacts_people.order(:first_name)
      respond_with @people
    end

    def show
      respond_with @person
    end

    def new
      @person = current_user.contacts_people.new()
      respond_with @person
    end

    def create
      @person = current_user.contacts_people.create(person_params)
      respond_with @person
    end

    def edit
      respond_with @person
    end

    def update
      @person.update(person_params)
      respond_with(@person)
    end

    def destroy
      @person.destroy
      respond_with @person
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_person
        @person = current_user.contacts_people.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def person_params
        params.require(:contacts_person).permit(:first_name, :last_name, :email)
      end

  end
end

app/views/contacts/people/_form.html.slim
= simple_form_for(@person, html: { class: 'form-horizontal' }) do |f|
  = f.error_notification

  .form-inputs
    = f.input :first_name
    = f.input :last_name
    = f.input :email

  .form-actions
    = link_to 'Cancel', contacts_people_path, class: 'btn'
    = f.button :submit

app/views/contacts/people/edit.html.slim
h1 Editing book

== render 'form'

app/views/contacts/people/index.html.slim
h1 Your Contacts

table.table
  thead
    tr
      th First Name
      th Last Name
      th Email
      th
      th
      th

  tbody
    - @people.each do |person|
      tr
        td = person.first_name
        td = person.last_name
        td = person.email
        td = link_to 'Show', person
        td = link_to 'Edit', edit_contacts_person_path(person)
        td = link_to 'Destroy', person, data: {confirm: 'Are you sure?'}, :method => :delete

br

= link_to 'Add Person', new_contacts_person_path, class: 'btn btn-primary'

app/views/contacts/people/new.html.slim
h1 New book

== render 'form'

app/views/contacts/people/show.html.slim
p#notice = notice

h2= "#{@person.first_name} #{@person.last_name}"

p= @person.email

= link_to 'Edit', edit_contacts_person_path(@person), class: 'btn btn-danger'
= link_to 'Back', contacts_people_path, class: 'btn'