config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'welcome#index'

  namespace :admin do
    resources :clients
  end

  namespace :culture do
    resources :books
  end

  namespace :contacts do
    resources :people
  end

end

app/models/culture.rb
module Culture
  def self.table_name_prefix
    'culture_'
  end
end

app/models/culture/book.rb
# == Schema Information
#
# Table name: culture_books
#
#  id            :uuid             not null, primary key
#  user_id       :uuid
#  title         :string           not null
#  description   :text
#  deleted_at    :datetime
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  custom_fields :jsonb
#
# Indexes
#
#  index_culture_books_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_2bd0fee54f  (user_id => users.id)
#

class Culture::Book < ActiveRecord::Base
  has_paper_trail meta: { user_id: :user_id }
  acts_as_paranoid

  DEFAULT_CUSTOM_FIELDS = { author: nil, publish_date: nil, rating: nil }

  belongs_to :user

  validates :title, :user_id, presence: true
end

app/controllers/culture/books_controller.rb
module Culture
  class BooksController < AuthenticatedController
    responders :flash, :collection

    before_action :set_book, only: [:show, :edit, :update, :destroy]

    def index
      @books = current_user.books.order(:title)

      respond_to do |format|
        format.html
        format.json
        format.pdf do
          render pdf: 'books.pdf',
            disposition: 'inline',
            template: 'culture/books/index.pdf.erb',
            layout: 'pdf_layout.html',
            footer: {
              html: {
                template: 'shared/footer'
              }
            }
        end
      end
    end

    def show
      # respond_with @book
      respond_to do |format|
        format.html
        format.json
        format.pdf do
          render pdf: 'book.pdf',
            disposition: 'inline',
            template: 'culture/books/show.pdf.erb',
            layout: 'pdf_layout.html'
        end
      end
    end

    def new
      @book = current_user.books.new()
      respond_with @book
    end

    def create
      @book = current_user.books.create(book_params)
      respond_with @book
    end

    def edit
      respond_with @book
    end

    def update
      @book.update(book_params)
      respond_with(@book)
    end

    def destroy
      @book.destroy
      respond_with @book
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_book
        @book = current_user.books.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def book_params
        params.require(:culture_book).permit(:title, :description)
      end

  end
end

app/helpers/books_helper.rb
# == Schema Information
#
# Table name: books
#
#  id          :uuid             not null, primary key
#  title       :string
#  description :text
#  deleted_at  :datetime
#
# Indexes
#
#  index_books_on_deleted_at  (deleted_at)
#

module BooksHelper
end

app/views/culture/books/_form.html.slim
= simple_form_for(@book, html: { class: 'form-horizontal' }) do |f|
  = f.error_notification

  .form-inputs
    = f.input :title
    = f.input :description

  .form-actions
    = link_to 'Cancel', culture_books_path, class: 'btn'
    = f.button :submit

app/views/culture/books/edit.html.slim
h1 Editing book

== render 'form'

app/views/culture/books/index.html.slim
h1 Listing books

table.table
  thead
    tr
      th Title
      th
      th
      th

  tbody
    - @books.each do |book|
      tr
        td = book.title
        td = link_to 'Show', book
        td = link_to 'Edit', edit_culture_book_path(book)
        td = link_to 'Destroy', book, data: {confirm: 'Are you sure?'}, :method => :delete

br

= link_to 'New Book', new_culture_book_path, class: 'btn btn-primary'

app/views/culture/books/index.pdf.erb
<% @books.each do |book| %>
  <div class="alwaysbreak">
    <div id="header">
      <%= wicked_pdf_image_tag 'logo.png' %>
    </div>
    <h1><%= book.title%></h1>
    <p><%= book.description %></p>
  </div>
<% end %>

app/views/culture/books/new.html.slim
h1 New book

== render 'form'

app/views/culture/books/show.html.slim
p#notice = notice

h2= @book.title

p= @book.description

- if @book.custom_fields.present?
  .custom-fields.well
    h4 Custom Fields
    dl
      - @book.custom_fields.sort.each do |cf|
        dt= cf[0].titleize
        dd= cf[1]


= link_to 'Edit', edit_culture_book_path(@book), class: 'btn btn-danger'
= link_to 'Back', culture_books_path, class: 'btn'

app/views/culture/books/show.pdf.erb
<h1><%= @book.title %></h1>

<div>
  <%= @book.description %>
</div>