config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'welcome#index'

  namespace :admin do
    resources :clients
  end

  namespace :culture do
    resources :books
  end

  namespace :contacts do
    resources :people
  end

end

app/views/layouts/_contact_links.html.slim
li.dropdown class=("#{'active' if params[:controller].starts_with?('contacts/')}")
  a.dropdown-toggle aria-expanded="false" data-toggle="dropdown" href="#"
    | Contacts&nbsp;
    span.caret
  ul.dropdown-menu role="menu"
    li= link_to "People", contacts_people_path

app/views/layouts/_culture_links.html.slim
li.dropdown class=("#{'active' if params[:controller].starts_with?('culture/')}")
  a.dropdown-toggle aria-expanded="false" data-toggle="dropdown" href="#"
    | Culture&nbsp;
    span.caret
  ul.dropdown-menu role="menu"
    li= link_to "Books", culture_books_path

app/views/layouts/_messages.html.slim
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"
      button.close[type="button" data-dismiss="alert" aria-hidden="true"] ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.slim
nav.navbar.navbar-default.navbar-fixed-top
  .container-fluid
    .navbar-header
      button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      ul.nav.navbar-nav
        == render 'layouts/navigation_links'
      ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          == render 'layouts/user_links'
        - else
          li class=("#{'active' if current_page?(new_user_registration_path)}")
            = link_to "Sign Up", new_user_registration_path
          li class=("#{'active' if current_page?(new_user_session_path)}")
            = link_to "Log In", new_user_session_path

app/views/layouts/_navigation_links.html.slim
- if user_signed_in?
  - if current_user.super_admin?
    == render "layouts/super_admin_links"

  == render "layouts/culture_links"

  == render "layouts/contact_links"

li class=("#{'active' if current_page?(page_path('about'))}")
  = link_to 'About', page_path('about')

app/views/layouts/_super_admin_links.html.slim
li.dropdown
  a.dropdown-toggle aria-expanded="false" data-toggle="dropdown" href="#"
    | ADMIN&nbsp;
    span.caret
  ul.dropdown-menu role="menu"
    li= link_to "Manage Clients", admin_clients_path

app/views/layouts/_user_links.html.slim
li.dropdown
  a.dropdown-toggle aria-expanded="false" data-toggle="dropdown" href="#"
    = current_user.email
    | &nbsp;
    span.caret
  ul.dropdown-menu role="menu"
    li
      = link_to edit_user_registration_path do
        i.dropdown-icon.fa.fa-edit
        | &nbsp;Edit Profile

    li.divider
    li
      = link_to destroy_user_session_path, method: :delete do
        i.dropdown-icon.fa.fa-power-off
        | &nbsp;Log Out

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    /! Force latest IE rendering engine & Chrome Frame.
    meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1"

    /! Encoding
    meta charset="utf-8"

    /! Viewport
    meta name="viewport" content="width=device-width, initial-scale=1.0"

    /! Identity
    title Rails Playground
    meta name="description" content="Demonstrate and experiment with Rails"
    meta name="author" content="Crispin Cornett"

    /! Security
    = csrf_meta_tags

    /! JavaScripts
    = javascript_include_tag 'application', 'data-turbolinks-track' => true

    /! Stylesheets
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true

  body
    header
      == render 'layouts/navigation'

    main[role="main"]
      .container
        == render 'layouts/messages'
        == yield